#!/bin/sh -e

PREREQS=""

prereqs()
{
	echo "$PREREQS"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /bin/find /usr/local/bin/find
copy_exec /sbin/fsck
copy_exec /sbin/fsck.ext4
copy_exec /sbin/fsck.fat
copy_exec /sbin/fsck.vfat

SOURCE=/usr/local/live/patch/
for FILE in $(find $SOURCE -type f | sed "s|^$SOURCE||")
do
	copy_file patch $SOURCE/$FILE /patch/$FILE
done
